version: '3.8'  # Use the desired Docker Compose version

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

services:
  redis:
    restart: always
    container_name: netprobe-redis
    image: "redis:latest"
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf
    networks:
      - custom_network  # Attach to the custom network

  netprobe:
    restart: always
    container_name: netprobe-probe
    build: .
    volumes:
      - .:/netprobe_lite
    environment:
      MODULE: "NETPROBE"
    networks:
      - custom_network  # Attach to the custom network

  presentation:
    restart: always
    container_name: netprobe-presentation
    build: .
    volumes:
      - .:/netprobe_lite
    environment:
      MODULE: "PRESENTATION"
    networks:
      - custom_network  # Attach to the custom network

  prometheus:
    restart: always
    container_name: netprobe-prometheus
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - custom_network  # Attach to the custom network

  grafana:
    restart: always
    image: grafana/grafana-enterprise
    container_name: netprobe-grafana
    volumes:
      - ./config/grafana/datasources/automatic.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - ./config/grafana/dashboards/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./config/grafana/dashboards/netprobe.json:/var/lib/grafana/dashboards/netprobe.json
    ports:
      - '3001:3000'
    networks:
      - custom_network  # Attach to the custom network
